app: FreeCAD-#NAME#
binpatch: true

ingredients:
  dist: trusty
  sources: 
    - deb http://archive.ubuntu.com/ubuntu/ trusty main universe
  ppas:
    - freecad-maintainers/freecad-daily
  packages:
    - freecad-daily
    # - calculix-ccx
    - appmenu-qt
  pretend:
    - libfontconfig1 2.11.0-0ubuntu4
  script:
    - rm -f freecad-daily*amd64.deb
    # try to restore the original package to prevent repeated download
    - ! test -f tmp/freecad-daily*.deb || mv tmp/freecad-daily*.deb .
  post_script:
    - mkdir -p tmp
    # save the original package for future redo
    - mv freecad-daily*.deb tmp/
    # replace the freecad deb package with our custom build
    - cp $HOME/pbuilder/trusty_result/freecad-daily*amd64.deb .

script:
  # install any workbench required
  - ../../../../../installwb.sh
  # resume setup just like FreeCAD-nightly
  - cp ./usr/share/applications/freecad-daily.desktop .
  - ln -s freecad-daily.desktop freecad-#NAME#.desktop
  - sed -i -e 's@FreeCAD Daily@FreeCAD@g' freecad-daily.desktop
  - sed -i -e 's@/usr/bin/@@g' freecad-daily.desktop
  - sed -i -e 's@Path=@# Path=@g' freecad-daily.desktop
  # - sed -i -e 's@Icon=freecad@Icon=freecad-daily@g' freecad-daily.desktop
  - cp ./usr/share/icons/hicolor/64x64/apps/freecad-daily.png .
  - mv ./usr/lib/lapack/*.so* ./usr/lib/
  - mv ./usr/lib/libblas/*.so* ./usr/lib/
  - # Dear upstream developers, please use relative rather than absolute paths
  - # then binary patching like this will become unneccessary
  - find usr/ -type f -exec sed -i -e "s@/usr/lib/freecad-daily@././/lib/freecad-daily@g" {} \;
  - find usr/ -type f -exec sed -i -e "s@/usr/share/freecad-daily@././/share/freecad-daily@g" {} \;
  - ( cd ./usr/lib/freecad-daily/ ; ln -s ../../share/ . ) # Why?
